export default [
  {
    name: "name",
    label: "Employee Name",
    placeholder: "Enter Employee name",
    tooltipText: "Employee Name",
    // parentTab: "General",
    tabName: "Identifier_tab",
    readOnly: false,
    type: "text",
    validationType: "string",
    validations: [
      // {
      //   type: "required",
      //   params: ["This field is required"],
      // },
      // {
      //   type: "matches",
      //   params: [
      //     "^[0-9]{0}$|^[0-9]{8}$|^[0-9]{12}$|^[0-9]{14}$",
      //     "gtin should be 8 or 12 or 14 character & should be number.",
      //   ],
      // },
    ],
  },
  {
    name: "phoneNumber",
    label: "Phone Number",
    placeholder: "Enter Phone Number",
    tooltipText: "Phone Number",
    // parentTab: "General",
    tabName: "Identifier_tab",
    readOnly: false,
    type: "number",
    validationType: "string",
    validations: [
      {
        type: "required",
        params: ["This field is required"],
      },
        {
            type: "matches",
            params: [
                "^[0-9]{0}$|^[0-9]{8}$|^[0-9]{12}$|^[0-9]{14}$",
                "gtin should be 8 or 12 or 14 character & should be number.",
            ],
        },
    ],
  },
  {
    name: "email",
    label: "Email",
    placeholder: "Enter Email",
    tooltipText: "Email",
    // parentTab: "General",
    tabName: "Identifier_tab",
    readOnly: false,
    type: "text",
    options: [],
    validationType: "",
    validations: [],
    validations: [
      {
        type: "required",
        params: ["This field is required"],
      },
    ],
  },
  {
    name: "gender",
    label: "Gender",
    placeholder: "Select Gender",
    tooltipText: "Gender",
    // parentTab: "General",
    tabName: "Identifier_tab",
    readOnly: false,
    type: "select",
    options: [
      { value: "male", label: "Male" },
      { value: "female", label: "Female" },
    ],
    validationType: "",
    validations: [
      {
        type: "required",
        params: ["This field is required"],
      },
    ],
  },
  {
    name: "designation",
    label: "Designation",
    placeholder: "Select Designation",
    tooltipText: "Designation",
    // parentTab: "General",
    tabName: "Identifier_tab",
    readOnly: false,
    type: "select",
    options: [
      { value: "developer", label: "Developer" },
      { value: "tester", label: "Tester" },
    ],
    validationType: "",
    validations: [
      {
        type: "required",
        params: ["This field is required"],
      },
    ],
  },
  //   {
  //     name: "address",
  //     label: "Address",
  //     placeholder: "Enter Address",
  //     tooltipText: "Address",
  //     // parentTab: "General",
  //     tabName: "Identifier_tab",
  //     readOnly: false,
  //     type: "textarea",
  //     validationType: "string",
  //     validations: [],
  //   },
  {
    name: "postalAddress[0]",
    subsection: "Postal Address",
    subSectionTooltipText: "Postal Address",
    tabName: "Marketing_tab",
    placeholder: "Line 1",
    readOnly: false,
    type: "text",
    validations: [
      {
        type: "required",
        params: ["This field is required"],
      },
    ],
  },
  {
    name: "postalAddress[1]",
    subsection: "Postal Address",
    tabName: "Marketing_tab",
    placeholder: "Line 2",
    readOnly: false,
    type: "text",
    validations: [
      {
        type: "required",
        params: ["This field is required"],
      },
    ],
  },
  {
    name: "postalAddress[2]",
    subsection: "Postal Address",
    tabName: "Marketing_tab",
    placeholder: "Line 3",
    readOnly: false,
    type: "text",
    validations: [
      {
        type: "required",
        params: ["This field is required"],
      },
    ],
  },
  {
    name: "postalAddress[3]",
    subsection: "Postal Address",
    tabName: "Marketing_tab",
    placeholder: "Line 4",
    readOnly: false,
    type: "text",
    validations: [
      {
        type: "required",
        params: ["This field is required"],
      },
    ],
  },
  {
    name: "bgColor",
    label: "_Background Color",
    placeholder: "",
    tooltipText: "Background Color",
    tabName: "Marketing_tab",
    // section: "Custom header",
    // sectionTooltipText: "Custom Header",
    readOnly: false,
    type: "color",
  },
  {
    name: "salary",
    label: "Salary",
    placeholder: "Enter Salary",
    tooltipText: "Salary",
    // parentTab: "General",
    tabName: "Identifier_tab",
    readOnly: false,
    type: "number",
    validationType: "string",
    // validations: [],
    validations: [
      {
        type: "required",
        params: ["This field is required"],
      },
    ],
  },
  {
    name: "Isuseractive",
    label: "Is User Active",
    placeholder: "",
    tooltipText: "User Active",
    // parentTab: "General",
    tabName: "Identifier_tab",
    readOnly: false,
    type: "switch",
  },
];
